package it.polimi.ingsw.Server.Messages.Events.Internal;

import it.polimi.ingsw.Model.Model;
import it.polimi.ingsw.Model.ModelWrapper;
import it.polimi.ingsw.Server.Messages.Events.ClientEvent;

/**
 * This Event is generated by {@link it.polimi.ingsw.Model.ModelWrapper} upon usage of
 * {@link it.polimi.ingsw.Model.ModelWrapper#editModel(ModelWrapper.ModelModifier, boolean)}.
 * This event contains a copy of the updated model, and is distributed to all players in a lobby
 */
public class ModelUpdateEvent implements ClientEvent {
    private final Model update;

    /**
     * Ship an updated model as an event
     * @param update reference to the updated model
     */
    public ModelUpdateEvent(Model update) {
        this.update = update;
    }

    /**
     * Get the {@link Model} object
     * @return a reference to the stored {@link Model}
     */
    public Model getModel() {
        return update;
    }
}
