name: Maven Package

on:
  push:
    branches:
      [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
          distribution: adopt
          server-id: github
      – name: Build with Maven.
        run: mvn clean package deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
